library(dplyr)

### Data processing helper functions
# Get_obs_by_bin() creates a preliminary data frame with multiple columns to be fed into ggplot graph-generating functions
#   data: dataset (e.g. generated by mock_data)
#   cat_var: character string, name of the variable to bin
#   cat_label: character string, e.g. ("Overdue", "0-30", "31-60", "61-90", "91-180", or "Over 180")
#   loan_type = character string, type of loan
#   num_loans = numeric, number of loans under each specific maturity label and loan type
#   amount_borrowed = numeric, total amount borrowed for specific maturity label and loan type
#   amount_owe = numeric, total amount owed for specific maturity label and loan type
Get_obs_by_bin <- function(data, cat_var="until_due_days", cat_label="Other", cat_min=-1e5, cat_max=1e5, summarise_func=n) {
  num_fin_types <- length(unique(data[['loan_type']]))
  x_categ_labs <- c(data[[cat_var]])
  maturity <- c(rep(cat_label, num_fin_types))
  aggregation <- "aggregate"

  if (identical(summarise_func, aggregation)) {
    summarise_func <- aggregate(data$loan_borrowed, list(data$cat_label), FUN=sum)
  }

  out_data <- data.frame(maturity,
    filter(data, x_categ_labs >= cat_min & x_categ_labs <= cat_max) %>% 
      group_by(loan_type) %>% 
      summarise(
        num_loans = summarise_func(),
        amount_borrowed = sum(loan_borrowed),
        amount_owe = sum(loan_owe),
        ir_w_borrow = weighted.mean(loan_rate, loan_borrowed),
        share_late = mean(until_due_days < 0),
        share_late_w_owe = sum(loan_overdue) / sum(loan_owe),
        share_late_30 = mean(until_due_days < -30),
        wshare_late_30_w_owe = sum(loan_overdue_30) / sum(loan_owe)
      )
  ) 
  return(out_data)
}

# Prep_mat_bin_data() uses the Get_obs_by_bin function and creates a dataframe encapsulating all data across all maturity labels
#   data: dataset, such as that generated like mock_data
Prep_mat_bin_data <- function(data) {
  c1 = Get_obs_by_bin(data, cat_label="Overdue", cat_max = 0)
  c2 = Get_obs_by_bin(data, cat_label="0-30", cat_min = 1, cat_max = 30)
  c3 = Get_obs_by_bin(data, cat_label="31-60", cat_min = 31, cat_max = 60)
  c4 = Get_obs_by_bin(data, cat_label="61-90", cat_min = 61, cat_max = 90)
  c5 = Get_obs_by_bin(data, cat_label="91-180", cat_min = 91, cat_max = 180)
  c6 = Get_obs_by_bin(data, cat_label="Over 180", cat_min = 181)
  result <- rbind(c1, c2, c3, c4, c5, c6)
}
